linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  disable:
    - depguard
    - gci
    - godox
    - goerr113
    - gosmopolitan
    - gomnd
    - interfacebloat
    - ireturn
    - musttag
    - noctx
    - nonamedreturns
    - paralleltest
    - tagalign
    - varnamelen
linters-settings:
  lll:
    # max line length, lines longer will be reported. Default is 120.
    line-length: 160

  nestif:
    # Minimal complexity of if statements to report. Default is 5
    min-complexity: 7

  wsl:
    # Allow assignments to be cuddled with other blocks as it generates unnecessary spaces between calls with assignment and warning/info log generation calls
    allow-assign-and-anything: true
    # Allow declaration of variables to be cuddled
    allow-cuddle-declarations: true

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - dupl
        - exhaustruct
        - forcetypeassert
        - funlen
        - goconst
        - lll
    - linters:
        - exhaustruct
      text: "core.EvtMeasureDataSingle"